[project]
name = "claude-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "danu", email = "dannyatcheson1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.8.0",
    "chess>=1.11.2",
]

[project.scripts]
claude-chess = "claude_chess.cli:main"

[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
